Update ssh_checkproxy to check for yes/no output
I prefer that the individual domain scripts return non-zero only when
they fail to function. By requiring a specific output on stdout, I can
tell the difference between an explicit "no" from the script vs an
effective "I don't know" because the script didn't work.

ssh still only looks at exit status, so this main ssh_checkproxy script
takes the "yes"/"no"/failure result and turns it into a 0 or a 1 exit
status.

diff --git a/local/bin/ssh_checkproxy b/local/bin/ssh_checkproxy
--- a/local/bin/ssh_checkproxy
+++ b/local/bin/ssh_checkproxy
@@ -27,11 +27,24 @@ if [ ! -f "$checkproxy" ]; then
 fi
 
 # run the domain drop-in checking script
-rval=0; "$checkproxy" || rval="$?"
+rval=0; stdout="$("$checkproxy")" || rval="$?"
 
-# exit with the value ssh expects depending on the drop-in return value
+# exit with the value ssh expects
+# depending on the drop-in return value and output
 if [ "$rval" -eq 0 ]; then
-	exit 0
+	if [ "$stdout" = "yes" ]; then
+		# enable proxy
+		exit 0
+	elif [ "$stdout" = "no" ]; then
+		# disable proxy
+		exit 1
+	else
+		# unexpected output,
+		# so we'll assume no proxy
+		exit 1
+	fi
 else
+	# the checkproxy script did not execute successfully,
+	# so we'll assume no proxy
 	exit 1
 fi
